[package]
name = "rssdump"
version = "0.1.0"
authors = ["Leonardo Lang <leonardoDOTlang@gmailDOTcom>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "*"
regex = "*"
ansi_term = "*"
